CONSTRUCT {
  ?pub dct:creator ?auts .
  ?ln rdf:first ?f ; rdf:rest ?r . # ln = list node
} {
  ?pub dct:creator ?auts .
  ?auts rdf:rest* ?ln .

  ?ln rdf:first ?f ; rdf:rest ?r .
} ORDER BY ?pub ?f
